name: conditional pull request
on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize
      - reopened
      - unlabeled
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "First Step"
      - name: Second step
        run: echo "Second Step"
  job02:
    if: "!contains(github.event.pull_request.labels.*.name, 'hotfix')"
    runs-on: ubuntu-latest
    steps:
      - name: Third step
        run: echo "Third Step"
        if: ${{ true }}
      - name: Fourth step
        run: echo "${{ toJSON(github.event.pull_request.labels.*.name) }}"
