name: conditional pull request
on:
  pull_request:
    types:
#      - opened
#      - labeled
#      - synchronize
#      - reopened
#      - unlabeled
      - closed
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "First Step"
      - name: Second step
        run: echo "Second Step"
        if: ${{ false }}
  job02:
    env:
      SKIP_LABEL_SET: ${{ contains(github.event.pull_request.labels.*.name, 'hotfix') }}
      GITHUB_BRANCH_MAIN: ${{ github.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Third step
        run: echo "Third Step."
      - name: Fourth step
        run: echo "$SKIP_LABEL_SET"
      - name: Fifth step
        run: echo ${{github.ref}}
      - name: SHOULD GET SKIPPED IF LABEL SET
        run: echo "Not Skipped"
        if: ${{ false == env.SKIP_LABEL_SET }} && {{ env.GITHUB_BRANCH_MAIN }}
  job03:
    if: |
      !contains(github.event.pull_request.labels.*.name, 'hotfix') &&
      github.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Third step
        run: echo "Third Step."
  job04:
    needs:
      - job03
    if: ${{ contains(needs.*.result, 'skipped') || contains(needs.*.result, 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Sixth Step
        run: echo "Sixth Step"
  job05:
    needs:
      - job04
    runs-on: ubuntu-latest
    steps:
      - name: Seventh Step
        run: echo "Seventh Step"