name: conditional pull request
on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize
      - reopened
      - unlabeled
      - closed
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "First Step"
      - name: Second step
        run: echo "Second Step"
        if: ${{ false }}
  job02:
    env:
      SKIP_LABEL_TRUE: ${{ contains(github.event.pull_request.labels.*.name, 'hotfix') }}
    runs-on: ubuntu-latest
    steps:
      - name: Third step
        run: echo "Third Step"
      - name: Fourth step
        run: echo "$SKIP_LABEL_TRUE"
      - name: Fifth step
        run: echo ${{github.ref}}
      - name: SHOULD GET SKIPPED
        run: echo "Hopefully Skipped"
        if: ${{ env.SKIP_LABEL_TRUE }}


